# Generated by Django 4.2.9 on 2026-03-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_size', models.BigIntegerField(help_text='Size in bytes')),
                ('file_type', models.CharField(help_text='audio or video', max_length=20)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
