# Generated by Django 4.2.9 on 2026-07-15 20:37

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_summary_user'),
    ]

    operations = [
        VectorExtension(),
        migrations.RemoveField(
            model_name='summary',
            name='user',
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='summaries.summary')),
            ],
            options={
                'db_table': 'document_chunks',
                'ordering': ['chunk_index'],
            },
        ),
    ]
