# Generated by Django 4.2.9 on 2026-07-15 21:03

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0003_remove_summary_user_documentchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=3072),
        ),
    ]
